export const actions = {
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    OPEN_CART: 'OPEN_CART',
    UPDATE_TO_CART: 'UPDATE_TO_CART',
    GET_BANNERS: 'GET_BANNERS',
}